# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Заголовок')),
                ('note', models.CharField(default='', max_length=3000, verbose_name='Описание')),
            ],
        ),
    ]
